# Generated by Django 3.2.16 on 2022-12-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
