# Generated by Django 3.2.16 on 2022-12-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0004_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_counter',
            field=models.IntegerField(default=0),
        ),
    ]
